name: Build and Test .NET API

on:
  push:
    branches: [master, dev]
    paths:
      - 'GiEnJul/**'

  pull_request:
    branches: [master, dev]
    paths:
      - 'GiEnJul/**'

  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
