name: Build and Test .NET API

on:
  push:
<<<<<<< HEAD:.github/workflows/main_backend.yml
    branches: [master]
    paths: "GiEnJul/**"

  pull_request:
    branches: [master]
    paths: "GiEnJul/**"
=======
    branches: [ master ]
    paths: 
      - 'GiEnJul/**'
      - '!GiEnJul/ClientApp/'
      
  pull_request:
    branches: [ master ]
    paths: 
      - 'GiEnJul/**'
      - '!GiEnJul/ClientApp/'
>>>>>>> 59567ffd264114a3952df7f6713b1e456171b0a2:.github/workflows/CI_backend.yml

  workflow_dispatch:

env:
  DOTNET_VERSION: "3.1.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up . NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
