name: Build frontend - React App and run tests

on:
  push:
    branches: [ master ]
    paths:
      - 'GiEnJul/ClientApp/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'GiEnJul/ClientApp/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: ./GiEnJul/ClientApp

      - name: Build
        run: npm run build
        working-directory: ./GiEnJul/ClientApp
        
      - name: Test
        run: npm test --watchAll=false
        working-directory: ./GiEnJul/ClientApp
