name: PROD - Build and Deploy Frontend to Azure

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "ClientApp/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        working-directory: ./ClientApp

      # Substitute variables here

      - name: Build
        run: npm run build
        working-directory: ./ClientApp

      - name: Tests
        run: npm test --watchAll=false
        working-directory: ./ClientApp

      - name: Deploy to Azure
        uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
        with:
          source-path: ./ClientApp/build
          sas-url: ${{secrets.DEPLOY_SAS_URL_PROD}}
